### ISSUE TITLE
compatibility with RaspberryPi (Debian)

### ISSUE THREAD

**Issue by sasagr** [justcop/Furk-Stream#1]
When I run the furk.py script I get this:
pi@raspberrypi:~/Furk-Stream $ python3 furk.py
Traceback (most recent call last):
  File "furk.py", line 26, in <module>
    logging.basicConfig(handlers=[logging.FileHandler("/config/home-assistant.log"),logging.FileHandler("/config/furk.log"),logging.StreamHandler()],format='%(asctime)s %(levelname)s (Furk) %(message)s',
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/config/home-assistant.log'

Not sure it can run on a raspberry pi.
As matter of fact if I try to install with pip3 install all the dependencies you mentioned in point 3. I get error for each of them.
The requirements.txt is installed correctly.
Can you pls advise?
Thanks

**Comment by sasagr** [comment]
adding some more info:
if I run pip install -r requirements.txt I get an error while trying to install guessit (print(*k) SyntaxError: invalid syntax).
If I run as pip3 then I have no error.

Then if I run python furk.py I get the message No module named guessit
if I run python3 furk.py I get the message in the previous post

**Comment by justcop** [comment]
Hi
Glad to hear you're interested in my script.
I'm super amateur and this is still a work in progress but I'd be keen to hear how you get on with it.
I've not looked at this for a few months now but there may well be a few bits that are setup for my own specific situation but I'll happily work with you to sort it.

can you try removing "logging.FileHandler("/config/home-assistant.log")" from line 26 of furk.py and seeing if that fixes it.

You are correct to run this with python3, it won't work on python2.

Currently the feature to redownload expired furk links does not work but they will still be automatically delted when they expire.

let me know how you get on.

**Comment by sasagr** [comment]
Thanks for your support. Appreciated. I have been using Furk service since many years and I just find out about your scripts and I think it could very useful so I can finally make a better use of Furk on my Apple TV in a different (and I think better) way.
I did what you suggested and got this:
pi@raspberrypi:~/Furk-Stream $ python3 furk.py
Traceback (most recent call last):
  File "furk.py", line 26, in <module>
    logging.basicConfig(handlers=[logging.FileHandler("/config/furk.log"),logging.StreamHandler()],format='%(asctime)s %(levelname)s (Furk) %(message)s',
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/config/furk.log'

Where should this /config/furk.log be located? I dont have it anywhere.

**Comment by sasagr** [comment]
ok, I did like this... I manually created a /config/furk.log file inside Furk-Stream profject folder and edited the furk.py to read ./config/furk.log and it exectuted the script but I got this:
pi@raspberrypi:~/Furk-Stream $ python3 furk.py
2021-07-29 10:53:53 INFO (Furk) 0 files have been processed.

I will better look at it because I actually had a .magnet file inside my torrent folder

**Comment by sasagr** [comment]
fixed the path in configs.py and got it working
pi@raspberrypi:~/Furk-Stream $ python3 furk.py
2021-07-29 11:10:45 INFO (Furk) Uploading "Avatar.2009.EXTENDED.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT" to Furk
2021-07-29 11:10:47 INFO (Furk) Checking Avatar.2009.EXTENDED.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT in Furk
2021-07-29 11:10:47 WARNING (Furk) furk file is not yet ready for download
2021-07-29 11:10:47 INFO (Furk) 0 files have been processed.

the file is in the active jobs in my furk.
Now to be be processed ... do I need to wait for it to finish and run again the furk.py I guess... will do that :)

**Comment by sasagr** [comment]
ok it worked... partially

pi@raspberrypi:~/Furk-Stream $ python3 furk.py
2021-07-29 11:27:02 INFO (Furk) Uploading "Avatar.2009.EXTENDED.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT" to Furk
2021-07-29 11:27:04 INFO (Furk) Checking Avatar.2009.EXTENDED.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT in Furk
2021-07-29 11:27:06 INFO (Furk) Completed processing Avatar.2009.EXTENDED.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT
chown: cannot access '/share/downloads': No such file or directory
2021-07-29 11:27:06 INFO (Furk) 1 files have been processed.

the movie folder with the .strm file is in the completed folder but it wasnt copied or moved to the final Movie folder.
These are the paths in the config:
torrents_path = './torrent'
completed_path = './completed'
TV_path = './TVShows'
media_path = './Movies'
also what does it mean ... chown: cannot access '/share/downloads': No such file or directory.. Is it a sort of buffer folder that I should manually create too?

**Comment by sasagr** [comment]
I created the /share/downloads folder inside the project folder and edited furk.py accordignly and I get this:
chown: changing ownership of './share/downloads': Operation not permitted
but eventually I see that after a couple of minuted the folder is copied to the Movie folder
Any suggestions about the ownership issue?

**Comment by justcop** [comment]
I've updated the script to change to a generic log file rather than one that suited my own setup.

I've also removed the line causing the error with ownership, that shouldn't be relevant to you either.

Please try the new version and let me know if it works

> Now to be be processed ... do I need to wait for it to finish and run again the furk.py I guess... will do that :)

Looks like I haven't yet implemented the feature for it to autorun after 10 minutes if the file is downloading as mentioned in step 8 in the readme, so yes, at the moment you'll either have to manually rerun or set cron to run the script often enough that the file will eventually download.

**Comment by justcop** [comment]
> the movie folder with the .strm file is in the completed folder but it wasnt copied or moved to the final Movie folder.

This should be done by radarr/sonarr. Now that I've removed the line that was not permitted, this should be allow the script to trigger radarr/sonarr to move these.

Please note I've also changed the configs template file slightly so make sure to update yours.

**Comment by sasagr** [comment]
did a pull and running the new furk.py I get this:
pi@raspberrypi:~/Furk-Stream $ python3 furk.py
  File "furk.py", line 27
    logging.basicConfig(handlers=[TimedRotatingFileHandler(os.path.dirname(__file__)), when="midnight", interval=1, backupCount=7),logging.StreamHandler()],format='%(asctime)s %(levelname)s (Furk) %(message)s',
                                                                                           ^
SyntaxError: invalid syntax

similar with linker.py
pi@raspberrypi:~/Furk-Stream $ python3 linker.py
  File "linker.py", line 27
    logging.basicConfig(handlers=[TimedRotatingFileHandler(os.path.dirname(__file__)), when="midnight", interval=1, backupCount=7),logging.StreamHandler()],format='%(asctime)s %(levelname)s (Furk Link-Check) %(message)s',
                                                                                           ^
SyntaxError: invalid syntax

**Comment by justcop** [comment]
ok i've just turned off the logging for now then until I hae time to work out what's causing that syntax error.

try again please

**Comment by sasagr** [comment]
it looks like there are still a few things:
pi@raspberrypi:~/Furk-Stream $ python3 furk.py
  File "furk.py", line 28
    level=logging.INFO,
    ^
IndentationError: unexpected indent

Initially I thought that maybe the cause of the previous syntax error but if I remove the indentiation I still get a syntax error:
pi@raspberrypi:~/Furk-Stream $ python3 furk.py
  File "furk.py", line 27
    logging.basicConfig(handlers=[TimedRotatingFileHandler(os.path.dirname(__file__)), when="midnight", interval=1, backupCount=7),logging.StreamHandler()],format='%(asctime)s %(levelname)s (Furk) %(message)s', level=logging.INFO, datefmt='%Y-%m-%d %H:%M:%S')
                                                                                           ^
SyntaxError: invalid syntax

so I completely # the code line
the furk.py then works but I get no output so I m not sure it is doing anything.

I get the errors in linker.py so I also # the code line of the logging, removing the indentation but I also get a new error:
pi@raspberrypi:~/Furk-Stream $ python3 linker.py
  File "linker.py", line 47
    for filename in Path(TV_path).rglob('*.strm')
                                                ^
SyntaxError: invalid syntax

Hope I m not giving too many headaches :)

**Comment by sasagr** [comment]
Ok. More feedbacks. I left the furk and linker py files with the initial changes we discussed at the beginning of this report before you pushed new versions and it works fine with both sonarr and radarr. I was also trying to play with the custom scripts in radarr and sonarr to run furk.py on grab/import but it does not work (never managed to use this custom scripts feature with any script). It would really nice to have all automatically done in sequence. FYI there is a similar project that I also use for premiumize that uses torrent blackhole and there is no manual script. https://github.com/dgalli1/DockerPremiumize

Pls let me know what u think. 
Thanks a lot for your project anyway. I m enjoying using it the way it is too

**Comment by justcop** [comment]
I've had some time to work on this now.

All bugs should now be fixed.

Re radarr and sonarr scripts, i'd imagine you've probably got a permissions issue, you'd need to check the radarr/sonarr logs to see the problem.

Let me know if it's working and I'll close the ticket

**Comment by sasagr** [comment]
both furk.py and linker.py run without error. I think you can close this issue and I will monitor it if any other issue.
Regarding adding furk.py as custom script on radarr, I m not sure it is permission issue. I m using radarr/sonarr in a docker and I mapped Furk-Stram for access and the files have 755 permission. Here is a screenshot if you have any idea.
![radarr_furk](https://user-images.githubusercontent.com/3427877/128723558-daaba632-5ef7-476d-9433-b519dba0c31c.jpg)

**Comment by sasagr** [comment]
the issue with the script seems to be that my radarr and sonarr installations are done with docker and they dont have python3 and pip3 with it so I have to do it manually eventually to be able to run the furk script within the radarr/sonarr container, though it still does not work from the connect, so I m giving up. I put a 10 min cron for furk.py and I m fine with it.
Just please let me know if the 10 min check will work, otherwise we can close the issue. 
Thanks for your support.
